//Elsa Gonsiorowski
//October 7, 2011
//Rensselaer Polytechnic Institute

#ifndef _gate_h
#define _gate_h

//ASSUPMTIONS
//- No gate uses its output as an input (doesn't send an event to itself)

//NOTES
//- never reallocate!


//file settings generated by preprocessor
//#define LINE_LENGTH 82       //15  82
//#define TOTAL_GATE_COUNT 211001  //25  211001
//#define NP_COUNT 24           //4   12   24
//#define LP_COUNT 8792           //7   17584  8792 //calculated from TOTAL_GATE_COUNT and NP
#define SOURCE_OUTPUTS 3305    //11  3305
#define SINK_INPUTS 3205
#define MAX_GATE_INPUTS 4    //4   4
//#define MAX_GATE_OUTPUTS 1   //5214


//Gate Types
#define GATE_TYPE_COUNT (12)
#define SOURCE_GATE (0)
#define SINK_GATE (1)
#define INPUT_GATE (2)
#define OUTPUT_GATE (3)
#define NOT_GATE (4)
#define DFF_GATE (5)
#define AND_GATE (6)
#define NAND_GATE (7)
#define OR_GATE (8)
#define NOR_GATE (9)
#define XOR_GATE (10)
#define XNOR_GATE (11)

#define SOURCE_ID (-1)
#define SINK_ID (-2)


#endif


